apiVersion: v1
kind: Service
metadata:
  labels:
    app: crisis-classification
  name: crisis-classification
spec:
  selector:
    app: crisis-classification
  ports:
  - name: http
    port: 8899
    protocol: TCP
    targetPort: 9999
